sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t tkurki/signalk-server .
# push image
- >
  docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  docker push tkurki/signalk-server
